export const LOAD_POSTS = 'LOAD_POSTS';
export const LOAD_POSTS_STARTED = 'LOAD_POSTS_STARTED';
export const LOAD_POSTS_ERROR = 'LOAD_POSTS_ERROR';
export const FETCH_SINGLE_POST_STARTED = 'FETCH_SINGLE_POST_STARTED';
export const FETCH_SINGLE_POST_ERROR = 'FETCH_SINGLE_POST_ERROR';
export const FETCH_SINGLE_POST_SUCESS = 'FETCH_SINGLE_POST_SUCESS';